eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  #端口号
  port: 8087
  #项目名，如果不设定，默认是 /
  #context-path: /
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.181.101:1521:orcl
    username: sxjyggfw
    password: QaoFEqnoFS9na1ML6TXaolnBiVm727urh+0HiermQ5rh3gRoHbV81C2Ef21bq+yBByduXe8ZDFgIwIJDvXDPqw==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK5oyDNLfdT7W7pVBeX6hspSyGLAAknO7Ts77gt+5UcFEJT85IQehxzBQsCqHgdJhwbB+9usRzajnRlpU5ldQM8CAwEAAQ==
    driverClassName : oracle.jdbc.driver.OracleDriver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j,config
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;
    logSlowSql: true
    ###############以上为配置druid添加的配置########################################
  redis:
    host: 192.168.70.158
    port: 6379
    password: admin
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1