spring:
  application:
    name: api-gateway
  profiles:
      active: pro
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis:
  mapper-locations: mapper/**/*Mapper.xml
  typeAliasesPackage: com.insigma.mvc.model
pagehelper:
    dialect: oracle
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
feign:
    hystrix:
      enabled: true
logging:
  level:
    root: info
    com.insigma: info
hystrix:
    command:
      default:
        execution:
          isolation:
              thread:
                 timeoutInMilliseconds: 245000
zuul:
    sensitiveHeaders:
    SendErrorFilter:
        error:
            disable: false
    SignatrueFilter:
        pre:
          disable: true
    TokenFilter:
        pre:
          disable: false

