spring:
  application:
    name: api-gateway
  profiles:
      active: dev
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
feign:
    hystrix:
      enabled: true
logging:
  level:
    root: info
    com.insigma: debug
hystrix:
    command:
      default:
        execution:
          isolation:
              thread:
                 timeoutInMilliseconds: 245000
zuul:
    sensitiveHeaders:  Cookie,Set-Cookie,Authorization
    SendErrorFilter:
        error:
            disable: false
    SignatrueFilter:
        pre:
          disable: false
    TokenFilter:
        pre:
          disable: false

