eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 7001
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
         git:
            uri: https://github.com/hellxz/SpringCloudlearn
            searchPaths: config-repo
            username: username
            password: password