eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  #端口号
  port: 8288
  #项目名，如果不设定，默认是 /
  #context-path: /
spring:
  datasource:
    url: jdbc:mysql://192.168.70.34:3306/jykn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: XdgX99yZ5I/anxglVP18j6fDhTxZG7RxAUQhdMbtIWC99BixAQ/uje7qeFpppV6/OKgRA6SMoF9tlMyqPQGDyQ==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIEcfWuNCJrUFxtYFti4t/2AlTDvjfkLrDeOZzLGW9hTCaznMhXrX55cWPUNoz92yxC7u9QE4TMSNsqS/j5Lvd8CAwEAAQ==
    driverClassName : com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j,config
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;
    logSlowSql: true
    ###############以上为配置druid添加的配置########################################
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
