spring:
  application:
    name: api-gateway
  profiles:
      active: dev
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
feign:
    hystrix:
      enabled: true
logging:
  level:
    root: info
    com.insigma: debug
  learning: trace
hystrix:
    command:
      default:
        execution:
          isolation:
              thread:
                 timeoutInMilliseconds: 245000

zuul:
    SendErrorFilter:
        error:
            disable: false
    # 不向后端服务传递的敏感头信息
    sensitiveHeaders:


